name: Issue Triage Bot

on:
    issues: 
        types: [opened]

permissions: 
    contents: read
    issues: write

jobs:
    welcome:
        runs-on: ubuntu-latest
        steps:
            - name: Comment on new issue
              uses: actions/github-script@v9
              # 1if: github.event.issue.author_association != 'OWNER'
              with:
                script: |
                    const fs = require('fs')

                    const {owner, repo, number } = context.issue
                    const author = context.payload.issue.user.login
                    const repoUrl = `${context.serverUrl}/${owner}/${repo}`

                    console.log('cwd = ', process.cwd())
                    console.log('contenido =', fs.readdirSync('.'))

                    const template = fs.readFileSync('.github/ISSUE_RESPONSES/welcome.md', 'utf8')

                    const body = template
                        .replaceAll('{{author}}', autor)
                        .replaceAll('{{repoUrl}}', repoUrl)
                        .replaceAll('{{runNumber}}', String(context.runNumber))
                        .replaceAll('{{runUrl}}', `${repoUrl}/actions/runs/${context.runId}`)

                    await github.rest.issues.createComment({
                        owner,
                        repo,
                        issue_number: number,
                        body
                    })
            
            